# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\AppBundle\Manager\UserManager:
    public: true
    class: App\AppBundle\Manager\UserManager
    arguments: ["@doctrine.orm.entity_manager", "@security.user_password_encoder.generic"]
  App\AppBundle\Manager\TaskManager:
    public: true
    class: App\AppBundle\Manager\TaskManager
    arguments: ["@doctrine.orm.entity_manager"]
  App\AppBundle\Fixtures\DataFixtures:
    public: true
    class: App\AppBundle\Fixtures\DataFixtures
    tags: ["@doctrine.fixture.orm","@security.user_password_encoder.generic"]



